### ISSUE TITLE
Vista Entrada de Datos

### ISSUE THREAD

**Issue by david-maestre-agencycic** [agency-cic/prueba-flutter-1#2]
Crear Formulario de Entrada de Datos

**Comment by Maqc0303** [comment]
Implementación de calendario para la asignación de la citas con sus respectivas fechas
![Imagen de WhatsApp 2024-03-19 a las 15 01 28_961713b1](https://github.com/agency-cic/prueba-flutter-1/assets/124466406/3bf624b0-8913-4d40-9f31-963c9941bd94)

**Comment by Maqc0303** [comment]
Se realizó las alertas de fecha no disponible para agendar, y la alerta si alguna empresa ya tiene su cita asignada, por lo tanto la app no lo dejará agregar una nueva 
1. Indica que la fecha no esta disponible:
![1](https://github.com/agency-cic/prueba-flutter-1/assets/124466406/62a6e84a-5e5a-4060-8310-4a6d727f3e73)
2. Alerta que la empresa ya tiene una cita asignada:
![2](https://github.com/agency-cic/prueba-flutter-1/assets/124466406/826e7c27-9a4c-45b4-9acf-d86457c2f488)
