### ISSUE TITLE
Vista Captura Info Complementaria 

### ISSUE THREAD

**Issue by david-maestre-agencycic** [agency-cic/prueba-flutter-1#3]
Crear Captura de Imagen / Ubicación

**Comment by juliangonzalez6** [comment]
Incorporación de un contenedor para subir imágenes desde la cámara y galería. Implemetación de campos para introducir información adicional de contacto como el correo electrónico o número de teléfono, cada uno con sus respectivas validaciones.
![Screenshot_20240319-140152](https://github.com/agency-cic/prueba-flutter-1/assets/112018830/d2a7e6c8-b730-4f1c-968f-91567e59dab8)

![Screenshot_20240319-143448](https://github.com/agency-cic/prueba-flutter-1/assets/112018830/97fb7c02-4257-423e-88c0-f6479d6d087f)

**Comment by juliangonzalez6** [comment]
Para tener la capacidad de seleccionar la ubicación, se utilizan los servicios de Google Maps. La aplicación se comunica por medio de una API que Google genera. Para obtener los valores de posición, es neceario interactuar por medio de toques con la pantalla, un marcador muestra el punto de donde se ha recolectado la posición.
![Screenshot_20240319-193059](https://github.com/agency-cic/prueba-flutter-1/assets/112018830/b117b190-ff3c-4fb5-a786-71fc42e7c075)
Se implementa una ventana de advertencia como mecanismo de información de usuario. Pues se ha definidio que no sea posible enviar los datos, si existen campos vacíos. 
![Screenshot_20240319-193104](https://github.com/agency-cic/prueba-flutter-1/assets/112018830/1025dedf-2c51-4e0c-a1f0-90ca028cf5bd)
Por último, se crea una pantalla adicional para ver la lista de comercio registrados, es decir, en ella esperan todos los datos que han sido ingresados por medio de las dos pantallas anteriores.
![Screenshot_20240319-193423](https://github.com/agency-cic/prueba-flutter-1/assets/112018830/816f7d9a-19dc-49d8-96dc-deff791002ec)
